# Generated by Django 4.1.7 on 2023-03-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.FileField(default=None, max_length=400, null=True, upload_to='photos/'),
        ),
    ]
