# Generated by Django 4.1.7 on 2023-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0002_post_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.DateField()),
                ('address', models.CharField(max_length=400)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
